# Generated by Django 4.2.7 on 2024-02-24 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_products_category_products_mark'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='video',
            field=models.TextField(blank=True, null=True),
        ),
    ]
