# Generated by Django 4.2.7 on 2024-02-24 13:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_products_video'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='products',
            table='Products',
        ),
    ]
