# Generated by Django 4.2.7 on 2024-02-24 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_alter_products_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='image',
            field=models.BinaryField(blank=True, default=None, null=True),
        ),
    ]
