# Generated by Django 4.2.7 on 2024-02-24 13:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_orderstatus_order_status'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='order',
            table='Orders',
        ),
        migrations.AlterModelTable(
            name='orderstatus',
            table='OrderStatus',
        ),
    ]
