# Generated by Django 4.2.7 on 2024-02-24 13:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_alter_order_table_alter_orderstatus_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='order',
            table='orders',
        ),
        migrations.AlterModelTable(
            name='orderitem',
            table='orders_items',
        ),
        migrations.AlterModelTable(
            name='orderstatus',
            table='order_status',
        ),
    ]
