# Generated by Django 4.2.7 on 2024-03-15 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_alter_order_table_alter_orderitem_table_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='is_paid',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
