# Generated by Django 4.2.7 on 2024-02-10 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_user_province'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='locality',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
