# Generated by Django 4.2.7 on 2024-02-24 13:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shoppingCart', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='shoppingcardcartitem',
            table='ShoppingCardCartItem',
        ),
        migrations.AlterModelTable(
            name='shoppingcarts',
            table='ShoppingCarts',
        ),
    ]
