# Generated by Django 4.2.7 on 2024-02-24 13:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shoppingCart', '0002_alter_shoppingcardcartitem_table_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shoppingcarts',
            options={'verbose_name': 'shopping_cart', 'verbose_name_plural': 'shopping_carts'},
        ),
        migrations.AlterModelTable(
            name='shoppingcardcartitem',
            table='shopping_card_cartItem',
        ),
        migrations.AlterModelTable(
            name='shoppingcarts',
            table='shopping_carts',
        ),
    ]
