# Generated by Django 4.2.7 on 2024-03-18 18:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shoppingCart', '0003_alter_shoppingcarts_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shoppingcarts',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
