# Generated by Django 4.2.7 on 2024-03-18 19:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shoppingCart', '0004_alter_shoppingcarts_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='shoppingcarts',
            name='session_id',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='shoppingcarts',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
