# Generated by Django 5.0.3 on 2024-03-28 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoppingCart', '0005_shoppingcarts_session_id_alter_shoppingcarts_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='shoppingcarts',
            name='shipping_cost',
            field=models.DecimalField(decimal_places=2, default=4.5, max_digits=10),
        ),
    ]
