# Generated by Django 5.0.3 on 2024-03-30 12:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shoppingCart', '0006_shoppingcarts_shipping_cost'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shoppingcarts',
            name='session_id',
        ),
    ]
