# Generated by Django 4.2.7 on 2024-02-24 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0002_categories_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='categories',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
