# Generated by Django 4.2.7 on 2024-02-24 13:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0003_categories_is_active'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categories',
            options={'verbose_name': 'Category'},
        ),
        migrations.AlterModelTable(
            name='categories',
            table='Categories',
        ),
    ]
